
/*
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

import java.util.Arrays;
import java.util.HashMap;

public class FindTheDifference {

	public static void main(String[] args) {
		System.out.println(findTheDifference("abcd", "abcde"));
	}

	public static char findTheDifference(String s, String t) {

		char[] sc = s.toCharArray();
		Arrays.sort(sc);
		s = new String(sc);

		char[] tc = t.toCharArray();
		Arrays.sort(tc);
		t = new String(tc);

		HashMap<Integer, String> hm = new HashMap<Integer, String>();
		for (int i = 0; i < s.length(); i++) {
			hm.put(i, s.substring(i, i + 1));
		}
		for (int i = 0; i < t.length() - 1; i++) {
			String search = t.substring(i, i + 1);
			if (hm.containsValue(search)) {
				if (!hm.get(i).equals(search)) {
					return search.charAt(0);
				}
			} else {
				return search.charAt(0);
			}

		}
		return t.charAt(t.length() - 1);
	}
}
